language: c

os:
  - osx
compiler:
  - clang

branches:
  only:
    - master
    - ci

script:
  - brew update && brew install harfbuzz fribidi freetype fontconfig && ./autogen.sh && ./configure
  - make

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#libass"
    on_success: change
    on_failure: always
