language: c

os:
  - linux
compiler:
  - gcc

branches:
  only:
    - master
    - ci

script:
  - sudo apt-get install -y fontconfig libfribidi-dev yasm && ./autogen.sh && ./configure
  - make

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#libass"
    on_success: change
    on_failure: always
