language: c

env:
  global:
   # Coverity tokeb
   - secure: "QFUmMNyjyhXhe+zBfGNgnrrgR9NTks90AU6BQXYCxBZm+aaRjjxkN+ITjTJeHxZJEVpqDf/gtidh6KriSWMWM2TcH+ZSsAkVym9XUdk+0Nglh/5mulp++LsbmsERhed5F4YvGS0UAcXPAAv/dESmiJY/EaDPVgXxbTFMa85c6H8="

os:
  - linux

branches:
  only:
    - master
    - ci
    - coverity_scan

script:
  - sudo apt-get install -y fontconfig libfribidi-dev yasm && ./autogen.sh && ./configure
  - make -j4

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#libass"
    on_success: change
    on_failure: always

addons:
  coverity_scan:
    project:
      name: "libass/libass"
      description: "Build submitted via Travis CI"
    build_command_prepend: "./configure; make clean"
    build_command:   "make -j4"
    branch_pattern: coverity_scan
